# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: my-app 
    - run: npm run build --if-present
      working-directory: my-app 
    - run: npm test
      working-directory: my-app 
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "u2017122@giki.edu.pk"
        git config --global user.name "u2017122"
        git remote set-url origin https://425c8a848f3d086052239156c18fb3909039e666@github.com/u2017122/assignment_2.git
        npm run deploy
